export const APPLY_FILTER_EXPLORE = 'APPLY_FILTER_EXPLORE';
export const EXPLORE_PAGE_LOADED = 'EXPLORE_PAGE_LOADED';
export const EXPLORE_PAGE_UNLOAD = 'EXPLORE_PAGE_UNLOAD';
export const CHANGE_MAIN_TAB = 'CHANGE_MAIN_TAB';
export const AUTH_SET_TOKEN = 'auth/SET_TOKEN';
export const AUTH_DISCARD_TOKEN = 'auth/DISCARD_TOKEN';
export const AUTH_SET_USER = 'auth/SET_USER';
